name: seagort
description: Run JavaScript on the backend/vm with Seagort.
version: 0.0.1-pre
repository: https://github.com/nima-code/seagort

executables:
  seagort:

environment:
  sdk: ^3.0.0

dependencies:
  ffi: ^2.1.0
  native_assets_cli: ^0.5.4
  native_toolchain_c: ^0.4.1
  path: ^1.9.0
  test: ^1.25.2

dev_dependencies:
  ffigen: ^11.0.0
